Dma controller
filip-stefanovic-bitsolver/mini_crypto_acc pull request #14
Opened 2023-04-04 19:35 UTC by filip-stefanovic-bitsolver

2023-04-04 19:47 UTC, filipbg92 requested changes

2023-04-04 19:47 UTC, filipbg92 commented on dma/rtl/axi_ar_ch.v
> +      next_descriptor <=0;
indent

2023-04-04 19:47 UTC, filipbg92 commented on dma/rtl/axi_ar_ch.v
> +      next_descriptor <=0;
use blocking assignment inside combo process

2023-04-04 19:47 UTC, filipbg92 commented on dma/rtl/axi_ar_ch.v
> +        rid_len[j] <= '0;
indent

2023-04-04 19:47 UTC, filipbg92 commented on dma/rtl/axi_ar_ch.v
> +                  arid <= descriptor_handler[79:72];
create constants for addressing bits inside descriptor handler, e.g. ID_MSB_POS and ID_LSB_POS

2023-04-04 19:47 UTC, filipbg92 commented on dma/rtl/axi_ar_ch.v
> +   if ((next_descriptor_d2 && next_descriptor_d1)||(!next_descriptor_d2 && next_descriptor_d1 && !next_descriptor))
missing reset

2023-04-04 19:47 UTC, filipbg92 commented on dma/rtl/axi_rd_ch.v
> +            else if (s == FIFO_N)
why does this exist?

2023-04-04 19:47 UTC, filipbg92 commented on dma/rtl/axi_rd_ch.v
> +always @(*)
missing comment - what is this process about, what does it do

2023-04-04 19:47 UTC, filipbg92 commented on dma/rtl/axi_rd_ch.v
> +            br <= br + 32;
doesn't seem 32 and it's multiples are required - divide each multiple of by 32 could be used instead and would use less bits

2023-04-05 09:58 UTC, AleksandarCurcin commented on dma/rtl/axi_ar_ch.v
> +      next_descriptor <=0;
translation

2023-04-05 09:59 UTC, AleksandarCurcin commented on dma/rtl/axi_ar_ch.v
> +      next_descriptor <=0;
translation

2023-04-05 10:29 UTC, AleksandarCurcin commented on dma/rtl/axi_ar_ch.v
> +   if ((next_descriptor_d2 && next_descriptor_d1)||(!next_descriptor_d2 && next_descriptor_d1 && !next_descriptor))
corrected

2023-04-05 10:29 UTC, AleksandarCurcin commented on dma/rtl/axi_ar_ch.v
> +      next_descriptor <=0;
corrected

2023-04-05 10:29 UTC, AleksandarCurcin commented on dma/rtl/axi_ar_ch.v
> +      next_descriptor <=0;
corrected

2023-04-05 10:30 UTC, AleksandarCurcin commented on dma/rtl/axi_ar_ch.v
> +                  arid <= descriptor_handler[79:72];
corrected, done

2023-04-05 10:38 UTC, AleksandarCurcin commented on dma/rtl/axi_rd_ch.v
> +            else if (s == FIFO_N)
corrected, else if is not necessery

2023-04-05 10:46 UTC, AleksandarCurcin commented on dma/rtl/axi_rd_ch.v
> +always @(*)
supplemented with commentary

2023-04-05 11:15 UTC, AleksandarCurcin commented on dma/rtl/axi_rd_ch.v
> +always @(posedge aclk or negedge arst_n)
If all FIFOs are used, this situation doesn't indicate that all FIFOs received all package with the appropriate ID. For this reason is necessary HIGH state for rready. E.g if starting transfer for two IDs (length is two) and we have two FIFOs, on first edge of clk FIFOs have one data of package with the appropriate ID, for two edges of clk comes another (last) data for first ID but if rready is LOW, data is lost. Because of that  it was taken, rready is HIGH always.

2023-04-10 09:15 UTC, filipbg92 approved these changes

2023-04-10 09:15 UTC, filipbg92 approved these changes

2023-04-10 09:16 UTC, closed without merging